## Project Management {#managment}

### *Introduction* {.unlisted .unnumbered}

While not directly related to data management, bad project management can cripple your ability to keep track of data, produce new data, and complete your interdisciplinary project in a timely manner. Good communication & project planning from the very beginning is critical for an interdisciplinary & highly collaborative project - as several teams will be bringing their own workflows & communication styles to the table.  For interdisciplinary projects in particular, each team member may bring their own assumptions regarding how a project should be managed, and assumptions made that may not align with the other team members.  

Without clearly defined goals & expectations, new pieces & components could be added to the project that completely exceed the original workload set in initial meetings.  It can be difficult to know when working with other disciplines if a new component is necessary & expected - or if it’s an extraneous addition.   It may also be possible that certain disciplines expect different outputs, and have differing expectations of what particular outputs mean (i.e  publication).  All of these concerns can lead to a chaotic working environment & massively slow down the project as communications break down.  

### *Questions to Consider* {.unlisted .unnumbered}

- What are the expected final outputs of this project?  Where and when will they be published? 
  - What will you need to create for the project to be considered successful?  
  - How will you share these creations with others?
- What are the project deadlines?  What does each team contribute to the expected outputs?  
  - Are particular outputs created solely by one team, or as a collaborative effort of more than one team? When are your team's deadlines?  When are the group's deadlines?
- How will communications be set up between team members?  How will files be shared? 
  - How frequently will group members need to communicate? (e.g. monthly updates, daily communications)
  - What tools best suit your communication needs?  (e.g. Google Suite, Slack, Teams)



### *Additional Resources* {.unlisted .unnumbered}

IHCR Workflow project charter

## Sharing among the group after the project {#sharing}

### *Sharing among the group after the project* {.unlisted .unnumbered}

At first glance, this may seem like a component that could be saved for the end of a project.  However, planning and forethought about who will be in charge of which components of project data is vital to the project’s eventual success.  It may seem simple, but particularly in highly collaborative projects, it is easy for data to be lost, not obtained, or left out of discussion or analysis because data was not properly shared between relevant researchers.  This is most salient in an interdisciplinary research group - where several team members may not even be aware that they are missing a critical piece of data generated by their collaborators from different domains. If this happens, inaccurate conclusions could be made, the working timeline extended, and the entire project risks creating useless outputs.  

### *Questions to Consider* {.unlisted .unnumbered}

- What data is each group collecting?  What data needs to be shared?  How and when will data be shared?
  - What file types will be used to store your data?  Will other group members be able to access them with appropriate permissions?
  - What will you use to make files available to other group members?  Will your communications tool work as a file sharing network? 
  - Will multiple people need to work on one file?   If so, how will this happen and what software will you use?
- How will the data be explained?  How much does each group member have to understand the whole dataset?  
  - What explanation or context would you need to give a particular group member so they can understand the data shared and do something with it?  



### *Additional Resources* {.unlisted .unnumbered}

IHCR Information storage and organization

IHCR Workflow preservation platform data

## Choosing from a variety of tools/methods {#tools}

### *Introduction* {.unlisted .unnumbered}

Many researchers have domain specific tools to accomplish tasks within an IHCR project.   In addition, there are a variety of data management tools/software, and it is highly likely that an interdisciplinary team will have varying skill sets & comfortability with these tools.  Even something as simple as data in spreadsheet applications can become challenging to manage and analyze if half the team is using Microsoft Excel, and the other half Google Sheets.  It may be the case that different interdisciplinary representatives can use what tools work best for them, or it may be the case that unity of tools & methods used is of the utmost importance.   Regardless of which one the project calls for, being clear on which tools are being used will ensure that difficulties in unifying & working with data are mitigated.  

While many tools are useful, and could speed up the project, careful consideration should be taken as to factors such as how long it would take to learn a new tool, and its availability to everyone on the project.   If you use a tool no one has time to learn, it may be useful, but unusable.   Be wary of complicated solutions that require much technical know-how, they are often not the best way to accomplish a task.  In addition, if new tools are not established & communicated , you may get incompatible files & workflows that will impede collaboration and slow progress.  


### *Questions to Consider* {.unlisted .unnumbered}

- Which tools will each team have to use?  What are the costs of these tools?  How much time will it take to learn these tools? 
  - What software does your team use to collect, analyze, and visualize data?  Do other teams know how to use this software and will they need to learn? 
- How much time will it take to move data from one tool to another? Will tools be used by multiple teams/disciplines, and if so what is the learning curve for their usage?
  - Do other group members need to learn and understand your software?  Is there a cost to access the software?


### *Additional Resources* {.unlisted .unnumbered}

IHCR Quantitative Data Processing

IHCR Workflow for historical/humanities data modeling

## Where will the data be stored?  Who has access?  {#data1}

### *Introduction* {.unlisted .unnumbered}

Effective data storage is a critical component for any successful research project, and its importance is only magnified with the volume & diversity of data that is typically involved with an interdisciplinary & highly collaborative research project.  Researcher choices about  data storage, including where it can be stored, who has access, and in what format, depend on discipline and available resources.  The group should lay out which pieces of data need to be readily shared & accessible by group members & collaborators - and find a platform that can allow for such sharing if it is needed.  Additional training, secure storage, and/or access restrictions may be required for data containing sensitive information.  Talk to the domain experts on each piece of data to be collected on your team, and consult with institutional support teams (e.g. IRB, research data services, IT) as needed.  If proper data storage is not discussed or considered, this can spiral into several competing versions of the datasets.  Not only does this slow data analysis, but can lead to inaccurate analysis. 


### *Questions to Consider* {.unlisted .unnumbered}

- Is this data sensitive?   Do you need approval for data security plans from another academic unit (e.g. IRB, Export Control, Research Compliance)?  What servers will the data be stored on?  Does the data need to be stored in a secure location? 
  - Does your data contain information on human research participants?  Does it contain classified information or is it associated with national security research?    
  - Is your data reasonably identifiable to certain individuals?  Based on the data and other openly available information could you guess who individuals are?  
- Does everyone on the project need access to a particular dataset?  Only some of them?  Which team members will have access to which files?   
  - Do you need special authorization or training to use a dataset, such as the (CITI) Human Subjects Research Basic Course or special human subject training? 
  - Will it be overwhelming if every group member has access to all of the data?  Can data access be compartmentalized for each team or members?  
  - What data needs to be shared among all group members?  

 

### *Additional Resources* {.unlisted .unnumbered}


IHCR Workflow Information storage and organization
